name: demo pipeline
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: [main, dev]
   # schedule:
   # - cron: '0 0 * * 0' # every Sunday at midnight
jobs: 
     
  setup_job:
    runs-on: ubuntu-latest  # macos-latest, windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: create file
        run: |
            touch github-action.txt
            ls -la
            echo "hello world"
            cat README.md              
  build_job:
    needs: 
      - setup_job
    runs-on: ubuntu-latest
    steps:
      - name: display hello
        run: echo Hello
      - name: Display github-action.txt
        run: cat github-action.txt 
  deploy_job:
    needs: setup_job
    runs-on: macos-latest
    steps:
      - run: echo hello mac
